version: '3'

tasks:
  build:
    cmds:
      - javac Main.java -d out -Werror
  run:
    cmds:
      - java Main.java
  edit:
    cmds:
      - $EDITOR .
  et:
    cmds:
      - $EDITOR Taskfile.yml
