version: '3'

tasks:
  build:
    cmds:
      - ./gradlew build
  run:
    sources:
      - src/main/java/net/thesimpleteam/picohttp/PicoHTTP.java
      - src/test/java/TestHTTP.java
    cmds:
      - ./gradlew test
  edit:
    cmds:
      - $EDITOR .
  et:
    cmds:
      - $EDITOR Taskfile.yml
